server.port = 8080
spring.application.name = producer
spring.kafka.producer.bootstrap-servers = localhost:9092

#Serialization
spring.kafka.producer.key-serializer = org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer = org.apache.kafka.support.serializer.JsonSerializer

#Spring Cloud Function
spring.cloud.function.definition = uppercase
spring.cloud.function.web.path = /uppercase